### ISSUE TITLE
Divi.conf

### ISSUE THREAD

**Issue by StPatrici** [7h3v01c3/Divi-Smart-Node-Update-Instructions#1]
In Divi.conf I see rpcport=51473 and another line port=51472. 
Port=51472 not in my old Divi.conf. Suppose to add?
In my old Divi.conf I see logins=1. Not in your new...should I delete?

**Comment by 7h3v01c3** [comment]
logips=1 is optional 

rpcport=51473
daemon=1
allows you to communicate with the Pi at the command line and anyway you want if you used Divinci on your pi too. 
https://github.com/hirscr/Divinci

port=51472 makes your local set up a full node and allows other wallets to connect and confirm blockchain data.

But you don't need port=51472
