### ISSUE TITLE
cpu issue

### ISSUE THREAD

**Issue by StPatrici** [7h3v01c3/Divi-Smart-Node-Update-Instructions#2]
After stopping server (dli stop) the cpu of the pi uses almost full memory. Mem. 948296.      Used 826208.
This is after 1 hour stopping server.
Also did increase swap to 2048.
Reason why pi uses so much cpu after stopping server?

**Comment by StPatrici** [comment]
Update: after 1,5 h memory reduced to 58688.

**Comment by 7h3v01c3** [comment]
it needs to close the blockchain but 40 minutes something is not right. I have not experienced that on any system, linux, windows, osx, raspbian. I mght again look at everything else running on the pi but I would also follow the below suggestion

I would post this here where the daemon GitHub and make sure you note that it is the 
Pi Arm Version of 1.0.8
https://github.com/DiviProject/Divi/releases/tag/v1.0.8
